[package]
name = "zed_actions"
version = "0.1.0"
edition.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[dependencies]
gpui.workspace = true
schemars.workspace = true
serde.workspace = true
uuid.workspace = true
workspace-hack.workspace = true

[lints]
workspace = true

