[package]
name = "vim"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/vim.rs"
doctest = false

[features]
neovim = []

[dependencies]
anyhow.workspace = true
collections.workspace = true
command_palette.workspace = true
command_palette_hooks.workspace = true
db.workspace = true
editor.workspace = true
gpui.workspace = true
itertools.workspace = true
language.workspace = true
log.workspace = true
multi_buffer.workspace = true
picker.workspace = true
project.workspace = true
regex.workspace = true
schemars.workspace = true
search.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
settings.workspace = true
task.workspace = true
text.workspace = true
theme.workspace = true
ui.workspace = true
util.workspace = true
vim_mode_setting.workspace = true
workspace.workspace = true
zed_actions.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
command_palette.workspace = true
editor.workspace = true
gpui.workspace = true
language.workspace = true
project.workspace = true
project_panel.workspace = true
settings.workspace = true
util.workspace = true
workspace.workspace = true
