# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "workspace-hack"

resolver = "2"
dep-format-version = "4"
workspace-hack-line-style = "workspace-dotted"

# this should be the same list as "targets" in ../rust-toolchain.toml
platforms = ["aarch64-apple-darwin"]

[traversal-excludes]
workspace-members = ["remote_server"]
third-party = [
    { name = "reqwest", version = "0.11.27" },
    # build of remote_server should not include scap / its x11 dependency
    { name = "scap", git = "https://github.com/zed-industries/scap", rev = "808aa5c45b41e8f44729d02e38fd00a2fe2722e7" },
    # build of remote_server should not need to include on libalsa through rodio
    { name = "rodio" },
]
