[package]
name = "icons"
version = "0.1.0"
edition.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/icons.rs"

[dependencies]
serde.workspace = true
strum.workspace = true
workspace-hack.workspace = true

[lints]
workspace = true

